version: "3.7"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: runner
    image: restapiproject-backend:latest
    ports:
      - 8000:8000
    volumes:
      - type: bind
        source: ./backend
        target: /opt/app
      - /opt/app/.venv
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: runner
    image: restapiproject-frontend:latest
    ports:
      - 3000:3000
    volumes:
      - type: bind
        source: ./frontend
        target: /opt/app
      - /opt/app/node_modules
